openapi: 3.0.0
info:
  title: User CRUD APIs
  version: 1.0.0

paths:
  /api/user:
    post:
      tags:
        - Users
      summary: Creates a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
              properties:
                name:
                  type: string
                email:
                  type: string
                address:
                  type: string
                phone:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
                      address:
                        type: string
                      phone:
                        type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
  /users/{userId}:
    get:
      summary: Get user
      parameters:
        - in: path
          name: userId
          required: true
          description: Id of the user
          schema:
            type: string
      responses:
        '200':
          description: User found
        '404':
          description: User not found
    put:
      summary: Replace a user
      parameters:
        - in: path
          name: userId
          required: true
          description: Id of the user
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - address
                - phone
              properties:
                name:
                  type: string
                email:
                  type: string
                address:
                  type: string
                phone:
                  type: string
      responses:
        '200':
          description: User updated
        '400':
          description: Invalid data
    patch:
      summary: Update a user
      parameters:
        - in: path
          name: userId
          required: true
          description: Id of the user
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                address:
                  type: string
                phone:
                  type: string
      responses:
        '200':
          description: User updated
        '400':
          description: Invalid data
    delete:
      summary: Delete a user
      parameters:
        - in: path
          name: userId
          required: true
          description: Id of the user
          schema:
            type: string
      responses:
        '200':
          description: User deleted
        '400':
          description: Invalid data
