openapi: 3.0.0

info:
  description: Node JS Test
  version: '1.0.0'
  title: Node JS Test
  contact:
    email: hafizabdullahtariq123@gmail.com
basePath: /
tags:
  - name: Users
    description: User CRUD APIs
schemes:
  - http
paths:
  /api/user:
    post:
      tags:
        - Users
      summary: Create user
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/definitions/User'
      responses:
        200:
          description: Success response
          schema:
            $ref: '#/definitions/SuccessResponse'
        400:
          description: Error response
          schema:
            $ref: '#/definitions/ErrorResponse'

definitions:
  SuccessResponse:
    type: object
    properties:
      success:
        type: boolean
        example: true
      message:
        type: string
        example: User created successfully
      user:
        type: object
        properties:
          id:
            type: number
            example: 1
          name:
            type: string
            example: John Doe
          email:
            type: string
            example: 'john@example.com'
          address:
            type: string
            example: USA
          phone:
            type: string
            example: 456112233
  ErrorResponse:
    type: object
    properties:
      success:
        type: boolean
        example: false
      message:
        type: string
        example: invalid request
  User:
    type: object
    required:
      - name
      - email
    properties:
      id:
        type: number
        example: 1
      name:
        type: string
        example: John Doe
      email:
        type: string
        example: 'john@example.com'
      address:
        type: string
        example: USA
      phone:
        type: string
        example: 456112233
